### ISSUE TITLE
what's wrong with my work?

### ISSUE THREAD

**Issue by welpher** [smrtlabs/smrt-gulp-r#5]
.pipe(rjs({
        "baseUrl": "./src/js",
        "name": require.resolve("almond")
    }))
get this error
[19:55:02] gulp-r Error: ENOENT, no such file or directory 'd:\workspace\xan\src\js\node_modules\almond\almond.js'

when i remove "name": require.resolve("almond")

get this error
[20:03:41] gulp-r Error: ERROR: module path does not exist: d:/workspace/xan/src/js/src/js/config.js for module named: config. Path is

**Comment by mcharytoniuk** [comment]
You need to install "almond" npm package to the project directory. You can use package.json to do add "almond" as a dependency and then invoke "npm install".

**Comment by welpher** [comment]
I have installed "almond" in D:/workspace/xan/node_modules but require.resolve("almond") get the path is 'd:\workspace\xan\src\js\node_modules\almond' and get  gulp-r Error: ENOENT, no such file or directory 'd:\workspace\xan\src\js\node_modules\almond\almond.js'

My js files all in '.src/js' folder , without almond, will get 
[09:24:42] gulp-r Error: ERROR: module path does not exist: d:/workspace/xan/src/js/src/js/config.js for module named: config. Path is
 relative to: d:/workspace/xan/src/js
double 'src/js'
like this https://github.com/jrburke/requirejs/issues/668

**Comment by mcharytoniuk** [comment]
Gulp-r does some assumptions about your project structure and may override some of optimizer options which does not necessarily fit every project. If you experience any issues like that you can use requirejs package directly inside gulp like this (which is completely fine) instead of `gulp-r`:

``` JavaScript
var requirejs = require("requirejs");

gulp.task("requirejs", function (done) {
  requirejs.optimize({
    // insert your options here
  }, done, done);
});
```

Please try to make sure all your paths are correct and use this official requirejs config file for reference: https://github.com/jrburke/r.js/blob/master/build/example.build.js

My basic r.js configuration looks like this:

``` JavaScript
{
    "baseUrl": "scripts",
    // "include": "node_modules/almond/almond.js",
    "include": "bower_components/almond/almond.js",
    "name": "your-main-app-file.js",
    "out": "dist/your-main-app-file.js",
    "paths": {
        // custom libraries paths
    }
}
```
